// Auto-generated by Aura Auto Atelier Image Processing Pipeline
// DO NOT EDIT DIRECTLY

export interface AssetImageMeta {
  src: string;
  alt: string;
  width: number;
  height: number;
  sizeKb: number;
}

import heroGtrRaw from './hero/hero_gtr_raw.jpg';
import heroGtrFinished from './hero/hero_gtr_finished.jpg';
import heroGtrRawCutout from './hero/hero_gtr_raw_cutout.webp';
import heroGtrFinishedCutout from './hero/hero_gtr_finished_cutout.webp';
import heroGtrShadow from './hero/hero_gtr_shadow.webp';
import heroVehicleCutout from './hero/hero_vehicle.webp';
import heroVehicleShadow from './hero/hero_vehicle_shadow.webp';
import gtrBeingPainted from './hero/gtr_being_painted.jpg';

import heroReflectionFinished from './hero/hero_reflection_finished.webp';
import heroReflectionRaw from './hero/hero_reflection_raw.webp';

// Service Cards Assets
import servicePPF from './services/service_ppf.webp';
import serviceCeramic from './services/service_ceramic.webp';
import serviceWrap from './services/service_wrap.webp';
import servicePaintCorrection from './services/service_paint_correction.webp';
import serviceBespokeInterior from './services/service_bespoke_interior.webp';
import serviceWindowTint from './services/service_window_tint.webp';

// Footer Atmosphere Asset
import footerShowcase from './footer/footer_showcase.webp';

export const HERO_ASSETS = {
  raw: heroGtrRaw,
  finished: heroGtrFinished,
  rawCutout: heroGtrRawCutout,
  finishedCutout: heroGtrFinishedCutout,
  gtrShadow: heroGtrShadow,
  cutout: heroVehicleCutout,
  shadow: heroVehicleShadow,
  beingPainted: gtrBeingPainted,
  reflectionFinished: heroReflectionFinished,
  reflectionRaw: heroReflectionRaw,
};

export const SERVICE_ASSETS = {
  ppf: {
    src: servicePPF,
    title: 'Paint Protection Film (PPF)',
    description: 'Self-healing, optically clear urethane shield protecting against stone chips, scratches, and road debris.',
  },
  ceramic: {
    src: serviceCeramic,
    title: 'Ceramic & Graphene Coating',
    description: 'Molecular nanoceramic bond delivering unmatched hydrophobicity, UV resistance, and mirror-like gloss.',
  },
  wrap: {
    src: serviceWrap,
    title: 'Bespoke Color Change Wrap',
    description: 'Premium vinyl & satin transformations executed with flawless panel disassembly and edge tucking.',
  },
  correction: {
    src: servicePaintCorrection,
    title: 'Multi-Stage Paint Correction',
    description: 'Precision jewel-polishing eliminating swirl marks, oxidation, and micro-marring to reveal deep luster.',
  },
  interior: {
    src: serviceBespokeInterior,
    title: 'Bespoke Interior Atelier',
    description: 'Leather conditioning, Alcantara revitalizing, and hydrophobic cabin surface shielding.',
  },
  tint: {
    src: serviceWindowTint,
    title: 'Nano-Ceramic Window Tint',
    description: 'Maximum infrared heat and UV rejection with crystal clear optical clarity and privacy.',
  },
};

export const FOOTER_ASSETS = {
  showcase: footerShowcase,
};

export default {
  hero: HERO_ASSETS,
  services: SERVICE_ASSETS,
  footer: FOOTER_ASSETS,
};
